name: Install

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release

    - name: build
      run: cmake --build build --target install -j

    - name: test
      run: |
        cd build
